### PR TITLE
Fix windows-x86 compilation

### PR DESCRIPTION
**Pull request by rivy**

### CODE REVIEW

**Comment by rivy** [comment]
This allows "windows-x86" compilation of the repository source, but there's still a problem. The compilation doesn't automatically build the "local" tools which it references via `${LBIN}`. So, for a successful build, an initial default compilation is required.

<details>
<summary>Log of a successful build</summary>

```shell
C:\>me configure && me
 [Configure] windows-x64-debug
     [Found] compiler: C/C++ Compiler: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe
     [Found] ejscript: Ejscript Language
     [Found] http: Http
     [Found] lib: Library Archive Tool: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\lib.exe
     [Found] link: Link Editor Program: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe
     [Found] mbedtls: MbedTLS Support: src\mpr-mbedtls
     [Found] mpr: Mpr
     [Found] osdep: Osdep
     [Found] pcre: Pcre
     [Found] rc: Windows Resource Compiler: C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\rc.exe
     [Found] ssl: Secure Socket Layer Interface (MbedTLS Support)
     [Found] zlib: Zlib
    [Create] build\windows-x64-debug\platform.me
    [Create] build\windows-x64-debug\inc\me.h
    [Create] start.me
      [Info] Type "me" to build.
      [Copy] build\windows-x64-debug\inc\osdep.h
      [Copy] build\windows-x64-debug\inc\embedtls.h
      [Copy] build\windows-x64-debug\inc\mbedtls-config.h
      [Copy] build\windows-x64-debug\inc\mbedtls.h
   [Compile] build\windows-x64-debug\obj\mbedtls.obj
   [Archive] build\windows-x64-debug\bin\libmbedtls.lib
      [Copy] build\windows-x64-debug\inc\mpr.h
   [Compile] build\windows-x64-debug\obj\mpr-mbedtls.obj
   [Archive] build\windows-x64-debug\bin\libmpr-mbedtls.lib
   [Compile] build\windows-x64-debug\obj\mprLib.obj
      [Link] build\windows-x64-debug\bin\libmpr.dll
      [Copy] build\windows-x64-debug\inc\pcre.h
   [Compile] build\windows-x64-debug\obj\pcre.obj
      [Link] build\windows-x64-debug\bin\libpcre.dll
      [Copy] build\windows-x64-debug\inc\http.h
   [Compile] build\windows-x64-debug\obj\httpLib.obj
      [Link] build\windows-x64-debug\bin\libhttp.dll
      [Copy] build\windows-x64-debug\inc\zlib.h
   [Compile] build\windows-x64-debug\obj\zlib.obj
      [Link] build\windows-x64-debug\bin\libzlib.dll
      [Copy] build\windows-x64-debug\inc\ejs.h
      [Copy] build\windows-x64-debug\inc\ejs.slots.h
      [Copy] build\windows-x64-debug\inc\ejsByteGoto.h
   [Compile] build\windows-x64-debug\obj\ejsLib.obj
      [Link] build\windows-x64-debug\bin\libejs.dll
   [Compile] build\windows-x64-debug\obj\ejsc.obj
      [Link] build\windows-x64-debug\bin\makeme-ejsc.exe
   [Compile] ejs.mod
      [Copy] build\windows-x64-debug\bin\ejs.testme.es
   [Compile] ejs.testme.mod
   [Compile] build\windows-x64-debug\obj\ejs.obj
      [Link] build\windows-x64-debug\bin\makeme-ejs.exe
      [Copy] extras => build\windows-x64-debug\bin
   [Compile] build\windows-x64-debug\obj\http.obj
      [Link] build\windows-x64-debug\bin\http.exe
      [Copy] install-certs => build\windows-x64-debug\bin
   [Compile] me.mod
      [Copy] pakrun => build\windows-x64-debug\bin
      [Copy] runtime => build\windows-x64-debug\bin
   [Compile] build\windows-x64-debug\obj\me.obj
      [Link] build\windows-x64-debug\bin\me.exe
  [Preserve] Active target build/windows-x64-debug/bin/me.exe as build/windows-x64-debug/bin/me.old
   [Compile] testme.mod
      [Copy] build\windows-x64-debug\inc\testme.h
   [Compile] build\windows-x64-debug\obj\testme.obj
      [Link] build\windows-x64-debug\bin\testme.exe
  [Preserve] Active target build/windows-x64-debug/bin/testme.exe as build/windows-x64-debug/bin/testme.old
      [Copy] build\windows-x64-debug\bin\testme.es
  [Complete] all

C:\>C:>me configure --platform windows-x86-release && me
 [Configure] windows-x86-release
     [Found] compiler: C/C++ Compiler: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX64\x86\cl.exe
     [Found] ejscript: Ejscript Language
     [Found] http: Http
     [Found] lib: Library Archive Tool: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX64\x86\lib.exe
     [Found] link: Link Editor Program: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX64\x86\link.exe
     [Found] mbedtls: MbedTLS Support: src\mpr-mbedtls
     [Found] mpr: Mpr
     [Found] osdep: Osdep
     [Found] pcre: Pcre
     [Found] rc: Windows Resource Compiler: C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\rc.exe
     [Found] ssl: Secure Socket Layer Interface (MbedTLS Support)
     [Found] zlib: Zlib
    [Create] build\windows-x86-release\platform.me
    [Create] build\windows-x86-release\inc\me.h
    [Create] start.me
      [Info] Type "me" to build.
     [Build] windows-x86-release
      [Copy] build\windows-x86-release\inc\osdep.h
      [Copy] build\windows-x86-release\inc\embedtls.h
      [Copy] build\windows-x86-release\inc\mbedtls-config.h
      [Copy] build\windows-x86-release\inc\mbedtls.h
   [Compile] build\windows-x86-release\obj\mbedtls.obj
   [Archive] build\windows-x86-release\bin\libmbedtls.lib
      [Copy] build\windows-x86-release\inc\mpr.h
   [Compile] build\windows-x86-release\obj\mpr-mbedtls.obj
   [Archive] build\windows-x86-release\bin\libmpr-mbedtls.lib
   [Compile] build\windows-x86-release\obj\mprLib.obj
      [Link] build\windows-x86-release\bin\libmpr.dll
      [Copy] build\windows-x86-release\inc\pcre.h
   [Compile] build\windows-x86-release\obj\pcre.obj
      [Link] build\windows-x86-release\bin\libpcre.dll
      [Copy] build\windows-x86-release\inc\http.h
   [Compile] build\windows-x86-release\obj\httpLib.obj
      [Link] build\windows-x86-release\bin\libhttp.dll
      [Copy] build\windows-x86-release\inc\zlib.h
   [Compile] build\windows-x86-release\obj\zlib.obj
      [Link] build\windows-x86-release\bin\libzlib.dll
      [Copy] build\windows-x86-release\inc\ejs.h
      [Copy] build\windows-x86-release\inc\ejs.slots.h
      [Copy] build\windows-x86-release\inc\ejsByteGoto.h
   [Compile] build\windows-x86-release\obj\ejsLib.obj
      [Link] build\windows-x86-release\bin\libejs.dll
   [Compile] build\windows-x86-release\obj\ejsc.obj
      [Link] build\windows-x86-release\bin\makeme-ejsc.exe
   [Compile] ejs.mod
      [Copy] build\windows-x86-release\bin\ejs.testme.es
   [Compile] ejs.testme.mod
   [Compile] build\windows-x86-release\obj\ejs.obj
      [Link] build\windows-x86-release\bin\makeme-ejs.exe
      [Copy] extras => build\windows-x86-release\bin
   [Compile] build\windows-x86-release\obj\http.obj
      [Link] build\windows-x86-release\bin\http.exe
      [Copy] install-certs => build\windows-x86-release\bin
   [Compile] me.mod
      [Copy] pakrun => build\windows-x86-release\bin
      [Copy] runtime => build\windows-x86-release\bin
   [Compile] build\windows-x86-release\obj\me.obj
      [Link] build\windows-x86-release\bin\me.exe
  [Preserve] Active target build/windows-x86-release/bin/me.exe as build/windows-x86-release/bin/me.old
   [Compile] testme.mod
      [Copy] build\windows-x86-release\inc\testme.h
   [Compile] build\windows-x86-release\obj\testme.obj
      [Link] build\windows-x86-release\bin\testme.exe
  [Preserve] Active target build/windows-x86-release/bin/testme.exe as build/windows-x86-release/bin/testme.old
      [Copy] build\windows-x86-release\bin\testme.es
  [Complete] all
```

</details>

If the initial default platform build isn't done, the "windows-x86" build fails at four points...

<details><summary>
compiling "ejs.mod"
</summary>

```shell
   [Compile] ejs.mod
Cannot access C:\Users\Roy\OneDrive\Projects\eg.makeme\makeme.repo\build\windows-x64-debug\bin\makeme-ejsc, errno 3
me: ERROR: Error with target: ejs.mod

Error Exception: Command failed: C:/Users/Roy/OneDrive/Projects/eg.makeme/makeme.repo/build/windows-x64-debug/bin/makeme-ejsc
Error Output: Cannot access command
Stack:
 [00] src/Builder.es, line 943, run, cmd.start(command, copt)
 [01] src/Script.es, line 514, run, makeme.builder.run(command, copt)
 [02] memory, line 4, default, run('"C:/Users/Roy/OneDrive/Projects/eg.makeme/makeme.repo/build/windows-x64-debug/bin/makeme-ejsc" --out "C:/Users/Roy/OneDrive/Projects/eg.makeme/makeme.repo/build/windows-x86-debug/bin/ejs.mod" --debug --bind --require null ejs.es')
 [03] src/Builder.es, line 1014, runTargetScript, result = eval('require ejs.unix\nrequire embedthis.me.script\n' +
 [04] src/Builder.es, line 286, buildScript, runTargetScript(target, 'build')
 [05] src/Builder.es, line 153, buildTarget, buildScript(target)
 [06] src/Builder.es, line 83, build, buildTarget(target)
 [07] src/Builder.es, line 800, process, build(goals)
 [08] src/MakeMe.es, line 175, main, builder.process(options.file, goals)
 [09] src/MakeMe.es, line 663, __initializer__, MakeMe().main()

me: ERROR: Building target ejs.mod
Exiting
```
</details>

<details><summary>
compiling "ejs.test.mod"
</summary>

```shell
   [Compile] ejs.testme.mod
Cannot access C:\Users\Roy\OneDrive\Projects\eg.makeme\makeme.repo\build\windows-x64-debug\bin\makeme-ejsc, errno 3
me: ERROR: Error with target: ejs.testme.mod

Error Exception: Command failed: C:/Users/Roy/OneDrive/Projects/eg.makeme/makeme.repo/build/windows-x64-debug/bin/makeme-ejsc
Error Output: Cannot access command
Stack:
 [00] src/Builder.es, line 943, run, cmd.start(command, copt)
 [01] src/Script.es, line 514, run, makeme.builder.run(command, copt)
 [02] memory, line 4, default, run('"C:/Users/Roy/OneDrive/Projects/eg.makeme/makeme.repo/build/windows-x64-debug/bin/makeme-ejsc" --debug --out "C:/Users/Roy/OneDrive/Projects/eg.makeme/makeme.repo/build/windows-x86-debug/bin/ejs.testme.mod" --optimize 9 ejs.testme.es')
 [03] src/Builder.es, line 1014, runTargetScript, result = eval('require ejs.unix\nrequire embedthis.me.script\n' +
 [04] src/Builder.es, line 286, buildScript, runTargetScript(target, 'build')
 [05] src/Builder.es, line 153, buildTarget, buildScript(target)
 [06] src/Builder.es, line 83, build, buildTarget(target)
 [07] src/Builder.es, line 800, process, build(goals)
 [08] src/MakeMe.es, line 175, main, builder.process(options.file, goals)
 [09] src/MakeMe.es, line 663, __initializer__, MakeMe().main()

me: ERROR: Building target ejs.testme.mod
Exiting
```
</details>

<details><summary>
compiling "me.mod"
</summary>

```shell
   [Compile] me.mod
Cannot access C:\Users\Roy\OneDrive\Projects\eg.makeme\makeme.repo\build\windows-x64-debug\bin\makeme-ejsc, errno 3
me: ERROR: Error with target: me.mod

Error Exception: Command failed: C:/Users/Roy/OneDrive/Projects/eg.makeme/makeme.repo/build/windows-x64-debug/bin/makeme-ejsc
Error Output: Cannot access command
Stack:
 [00] src/Builder.es, line 943, run, cmd.start(command, copt)
 [01] src/Script.es, line 514, run, makeme.builder.run(command, copt)
 [02] memory, line 4, default, run('"C:/Users/Roy/OneDrive/Projects/eg.makeme/makeme.repo/build/windows-x64-debug/bin/makeme-ejsc" --debug --out "C:/Users/Roy/OneDrive/Projects/eg.makeme/makeme.repo/build/windows-x86-debug/bin/me.mod" --optimize 9 paks/ejs.version/Version.es src/Builder.es src/Loader.es src/MakeMe.es src/Me.es src/Script.es src/Target.es')
 [03] src/Builder.es, line 1014, runTargetScript, result = eval('require ejs.unix\nrequire embedthis.me.script\n' +
 [04] src/Builder.es, line 286, buildScript, runTargetScript(target, 'build')
 [05] src/Builder.es, line 153, buildTarget, buildScript(target)
 [06] src/Builder.es, line 83, build, buildTarget(target)
 [07] src/Builder.es, line 800, process, build(goals)
 [08] src/MakeMe.es, line 175, main, builder.process(options.file, goals)
 [09] src/MakeMe.es, line 663, __initializer__, MakeMe().main()

me: ERROR: Building target me.mod
Exiting
```
</details>

<details><summary>
compiling "testme.mod"
</summary>

```shell
   [Compile] testme.mod
Cannot access C:\Users\Roy\OneDrive\Projects\eg.makeme\makeme.repo\build\windows-x64-debug\bin\makeme-ejsc, errno 3
me: ERROR: Error with target: testme.mod

Error Exception: Command failed: C:/Users/Roy/OneDrive/Projects/eg.makeme/makeme.repo/build/windows-x64-debug/bin/makeme-ejsc
Error Output: Cannot access command
Stack:
 [00] src/Builder.es, line 943, run, cmd.start(command, copt)
 [01] src/Script.es, line 514, run, makeme.builder.run(command, copt)
 [02] memory, line 4, default, run('"C:/Users/Roy/OneDrive/Projects/eg.makeme/makeme.repo/build/windows-x64-debug/bin/makeme-ejsc" --debug --out "C:/Users/Roy/OneDrive/Projects/eg.makeme/makeme.repo/build/windows-x86-debug/bin/testme.mod" --optimize 9 testme.es')
 [03] src/Builder.es, line 1014, runTargetScript, result = eval('require ejs.unix\nrequire embedthis.me.script\n' +
 [04] src/Builder.es, line 286, buildScript, runTargetScript(target, 'build')
 [05] src/Builder.es, line 153, buildTarget, buildScript(target)
 [06] src/Builder.es, line 83, build, buildTarget(target)
 [07] src/Builder.es, line 800, process, build(goals)
 [08] src/MakeMe.es, line 175, main, builder.process(options.file, goals)
 [09] src/MakeMe.es, line 663, __initializer__, MakeMe().main()

me: ERROR: Building target testme.mod
Exiting
```
</details>

Replacing `${LBIN}` with `${BIN}` within the "build" entry in the various ".me" scripts (*src/ejscript/ejscript.me*,  *src/tm/testme.me*, and *main.me*) for the four files allows successful compilation without the prior default platform compilation step.

**Comment by rivy** [comment]
Ping @dev-embedthis ... any comments?

**Comment by dev-embedthis** [comment]
Thanks for the reminder. We'll look into this and get back in the next few days.

Cheers

**Comment by dev-embedthis** [comment]
We use

    make boot

for a windows boot. This does a make boot first, then uses itself to do a release build.

**Comment by dev-embedthis** [comment]
The compiler warning fix and 'highentropyva' linker option look good.

We're in the middle of preparing 7.2 and so we've applied those manually instead of merging the pull request (we need to apply them upstream to other repos).

Let me know  if "make boot" solves the build issue for you.

**Comment by rivy** [comment]
`make boot` runs to completion, creating working build artifacts, but it doesn't build the `${LBIN}` tools needed for `me configure --platform windows-x86-release && me` to complete successfully. I still have to use a preliminary `me configure && me` prior to initiating the "windows-x86" build for a successful build.

**Comment by rivy** [comment]
Ping @dev-embedthis ... checking back in on this.

**Comment by dev-embedthis** [comment]
Cross compilation only does one pass and won't build local tools.

Try removing the --platform switch and it will build local tools I think.
You may also try providing multiple platform switches to get it to build for multiple platforms, though I've not tested this.

**Comment by rivy** [comment]
As I noted [above](https://github.com/embedthis/makeme/pull/95#issuecomment-522408578) ...
```shell
me configure && me
me configure --platform windows-x86-release && me
```
works, but I think it either 1) shouldn't be a necessary step at all (my preference), or 2) should output an error specifying that `me configure && me` is a necessary first step when the local tools are not available.

Notably...
```shell
make boot
me configure --platform windows-x86-release && me
```
*doesn't* compile (ie, `${LBIN}` tools are not installed by `make boot` {even though built locally}).

**Comment by dev-embedthis** [comment]
I need to understand your comments a bit more. When you say "installed" do you mean when you type "make install"?  or do you mean they don't get built under build/* ?

Also, you say there are 4 places that LBIN should be BIN, can you list those?

What is your native platform?  Is it windows-x64?   i.e. are you wanting cross compilation for x86 on a x64 system?  

Lastly, does this problem happen if you just build natively for windows-x64?  

Thanks

**Comment by rivy** [comment]
> I need to understand your comments a bit more. When you say "installed" do you mean when you type "make install"? or do you mean they don't get built under build/* ?

By "installed", I mean that `make boot` doesn't place the tools in a place that a subsequent `me configure --platform windows-x86-release && me` can use to successfully complete a build.

> Also, you say there are 4 places that LBIN should be BIN, can you list those?

The files are noted in the discussion above...

> What is your native platform? Is it windows-x64? i.e. are you wanting cross compilation for x86 on a x64 system?

Yes, "windows-x64" is the native system being used.
 
> Lastly, does this problem happen if you just build natively for windows-x64?

No, I noted that `me configure && me` (the native build kata) works.

**Comment by dev-embedthis** [comment]
Thanks for the answers. We cannot change BIN to LBIN as this will only work for you because you can run BIN/ executables on your system because X86 can run on X64. When doing cross compilation to dissimilar architectures, that won't work.

**Pull request closed without merging**
